#!/usr/bin/bash
#                                                 ----- Windows -----
#En python3.exe instalar pip,tk y agregar variables de entorno
pip install --upgrade pip
pip install numpy matplotlib opencv-python pillow jupyter
jupyter notebook
#                                                 ------ Linux ------
sudo apt-get install python3 python3-pip python3-tk
python3 -m pip install numpy matplotlib opencv-python pillow jupyter
#?jupyter notebook
