#!/usr/bin/bash
#                                                 ----- Windows -----
#En python3.exe instalar pip,tk y agregar variables de entorno
#                                                 ------ Linux ------
sudo apt-get install python3 python3-pip python3-tk
